### ISSUE TITLE
Edge masks

### ISSUE THREAD

**Issue by IrumaMegumi** [dddb11/MVSS-Net#10]
Can you give me a set of sample images of the original image, groundtruth, edge mask, and label?
I don't understand how to generate edge mask.

**Comment by IrumaMegumi** [comment]
That is, a Sobel or Canny at groundtruth?

**Comment by IrumaMegumi** [comment]
Or give me codes on processing groundtruth to edge mask?

**Comment by SunnyHaze** [comment]
https://github.com/dddb11/MVSS-Net/blob/15f723da7f24020fe15a8d4a97e0dc300e0b4af7/datasets/dataset.py#L67

**Comment by IrumaMegumi** [comment]
Thanks.

**Comment by SunnyHaze** [comment]
Of course, you can use Canny or Sobel to implement a similar function. The width of the edge musk can greatly affect the results.
