### ISSUE TITLE
cv2.resize error

### ISSUE THREAD

**Issue by IrumaMegumi** [dddb11/MVSS-Net#11]
When I use your code to train, I found an error nearly after an epoch, error: (-215:Assertion failed) !dsize.empty() in function 'resize'. How to solve it?

**Comment by IrumaMegumi** [comment]
I've repaired it. I will give a pull request recently.

**Comment by SunnyHaze** [comment]
I'm sorry for not responding promptly; I've been a bit busy lately. If it's already fixed, that's great. Thanks a lot for your coming PR.
