### ISSUE TITLE
关于损失的问题

### ISSUE THREAD

**Issue by JulieChoo** [dddb11/MVSS-Net#6]
博主您好，感谢你的工作。对我们的工作帮助很大。

我想请教下博主关于原作者论文中提及的对真图只做分类损失这个问题应该怎么实现？

因为训练的时候，一个batch中难免混有真图和伪造图，如果对真图只做分类损失，对假图做分类损失和分割损失，那么由于一个batch中真图假图占比不同，分类损失占比总损失又小，所以在batch间损失会有很大的震荡和波动，网络会难以优化学习。

期待您的答复！

**Comment by SunnyHaze** [comment]
你好，感谢你的关注！

原论文中的观点应为 真实图像 和 篡改图像均使用了分类损失和分割损失。从分割损失考虑相比于以前的研究只引入篡改图像，这样可以从一定程度上减少FP（假阳性），也是论文开头提到的。另一方面，分类损失的设计是为了弥补因为图像篡改检测大部分区域都被预测为0，导致少数的假阳性像素并不能贡献太多梯度，所以为了提高对于真实图片的收敛速度和准确率才单独设计了分类损失，相比于只使用分割损失是提高了模型对于假阳性的敏感程度。

希望能帮到你
