### ISSUE TITLE
想请问一下如何运行你的代码？

### ISSUE THREAD

**Issue by CongYep** [dddb11/MVSS-Net#8]

**Comment by SunnyHaze** [comment]
感谢你的关注！
Sorry，前两天有些忙，我今晚写个快速run 起来的教程。

**Comment by ZhangHuacong** [comment]
感谢你的回复。我注意到你的训练代码使用分布式机器来训练， 我这里只有单机的单卡或者4卡的3090服务器，不知道能不能适配跑起来。非常感谢你的工作，谢谢。



---原始邮件---
发件人: "Ma Xiaochen ***@***.***&gt;
发送时间: 2023年4月25日(周二) 晚上9:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dddb11/MVSS-Net] 想请问一下如何运行你的代码？ (Issue #8)




 
感谢你的关注！
 Sorry，前两天有些忙，我今晚写个快速run 起来的教程。

**Comment by SunnyHaze** [comment]
不太影响的，按照卡的数量修改运行时的命令行指令即可。已经上传最基本的运行教程，issue解决。
